### ISSUE TITLE
Bad peg or bad input causes out of memory error

### ISSUE THREAD

**Issue by jackc** [PuerkitoBio/pigeon#3] opened 2015-05-16 19:07 UTC
I spent the morning experimenting with pigeon. Very cool. My toy was a skeleton XML parser / pretty printer. I hacked on it enough to get a feel for pigeon.

One problem I ran into was if I fed an incomplete XML document into it (such as "<foo>bar"), it would crash with:

```
fatal error: runtime: out of memory
```

This was my peg file:

```
{
package main
}

Document <- el:Element EOF {
  return el, nil
}

Element <- _ oTag:OpeningTag body:(Element / TextNode)* cTag:ClosingTag _ {
  el := Element{name: oTag.(string)}

  for _, c := range body.([]interface{}) {
    el.children = append(el.children, c.(prettyPrinter))
  }
  return el, nil
}

OpeningTag <- '<' tag:TagName '>' {
  return tag, nil
}

ClosingTag <- "</" tag:TagName '>' {
  return tag, nil
}

TagName <- [a-z]i [a-z0-9]i* {
  return string(c.text), nil
}

TextNode <- [^<]+ {
  return TextNode(c.text), nil
}

_ "whitespace" <- [ \n\t\r]*

EOF <- !.
```

I don't know if this is a bug in my peg file or a bug in pigeon, but it really doesn't like running into an unexpected EOF. If it is a bad peg file, some sort of error or warning would be nice.

If it would help, you can see the whole repo here: https://github.com/jackc/pigeon-exp-xmlpp

**Comment by PuerkitoBio** [comment] 2015-05-16 19:53
Interesting, could you give it a try with the `wip-vm` branch of pigeon? It shouldn't require any change in your code, but the pigeon implementation uses a VM instead of recursive func calls (which I suspect is the cause of the OOM in your case).

That branch is not 100% ready to be merged in master, but I'd really appreciate that kind of feedback with an actual real case.

Thanks,
Martin

**Comment by jackc** [comment] 2015-05-16 21:39
Different stack trace, but it still crashes with OOM.

```
jack@edi:~/dev/go/src/github.com/jackc/xmlpp$ go generate && go build && ./xmlpp < test.xml 
fatal error: runtime: out of memory

runtime stack:
runtime.SysMap(0xc372590000, 0x498c0000, 0x59b200, 0x5a2db8)
	/usr/local/go/src/runtime/mem_linux.c:149 +0x98
runtime.MHeap_SysAlloc(0x5a84a0, 0x498c0000, 0x43aaa2)
	/usr/local/go/src/runtime/malloc.c:284 +0x124
runtime.MHeap_Alloc(0x5a84a0, 0x24c5f, 0x100000000, 0xc28867ef60)
	/usr/local/go/src/runtime/mheap.c:240 +0x66

goroutine 1 [running]:
runtime.switchtoM()
	/usr/local/go/src/runtime/asm_amd64.s:198 fp=0xc20802d118 sp=0xc20802d110
runtime.mallocgc(0x498be000, 0x0, 0x3, 0x7fa73232c000)
	/usr/local/go/src/runtime/malloc.go:199 +0x9f3 fp=0xc20802d1c8 sp=0xc20802d118
runtime.rawmem(0x498be000, 0x498be000)
	/usr/local/go/src/runtime/malloc.go:371 +0x39 fp=0xc20802d1f0 sp=0xc20802d1c8
runtime.growslice(0x4b7e60, 0xc2d9d70000, 0x1d6b2000, 0x1d6b2000, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/slice.go:83 +0x237 fp=0xc20802d250 sp=0xc20802d1f0
main.(*ϡvm).dispatch(0xc2080007e0, 0x0, 0x0)
	/home/jack/dev/go/src/github.com/jackc/xmlpp/xml.go:1307 +0x35a fp=0xc20802dc28 sp=0xc20802d250
main.(*ϡvm).run(0xc2080007e0, 0x596880, 0x0, 0x0, 0x0, 0x0)
	/home/jack/dev/go/src/github.com/jackc/xmlpp/xml.go:1249 +0x4eb fp=0xc20802ddf0 sp=0xc20802dc28
main.Parse(0x0, 0x0, 0xc208056000, 0x22, 0x600, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/jack/dev/go/src/github.com/jackc/xmlpp/xml.go:737 +0x191 fp=0xc20802de40 sp=0xc20802ddf0
main.ParseReader(0x0, 0x0, 0x7fa73233db10, 0xc208034000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/jack/dev/go/src/github.com/jackc/xmlpp/xml.go:722 +0x12f fp=0xc20802ded0 sp=0xc20802de40
main.main()
	/home/jack/dev/go/src/github.com/jackc/xmlpp/main.go:55 +0x86 fp=0xc20802df98 sp=0xc20802ded0
runtime.main()
	/usr/local/go/src/runtime/proc.go:63 +0xf3 fp=0xc20802dfe0 sp=0xc20802df98
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc20802dfe8 sp=0xc20802dfe0
```

**Comment by PuerkitoBio** [comment] 2015-05-16 21:42
Cool, thank, I'll debug it with the code from your repo.

**Comment by PuerkitoBio** [comment] 2015-05-22 02:59
Looks like the issue is with the TextNode rule, a bug in the inverted char class. Replacing [^<]+ with (!'<' .)+works. Not fixed yet but at least halfway there.

**Closed** 2015-05-22 03:09 UTC
